services:
  db:
    image: postgres:16
    volumes:
      - app_backend_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "docker"
    ports:
      - "5432:5432"

volumes:
  app_backend_postgres: